-- =============================================================================
-- SQL Fix: Align database index names with enterprise convention
-- Convention: ix_{table}_{column} / uq_{table}_{column}
--
-- Usage:
--   psql -d yourdb -f fix_index_names.sql
--   sqlite3 your.db < fix_index_names.sql
--
-- Generated by comparing actual DB state (13 Jun 2026 dump) against migration
-- code (001-011) after enterprise naming refactor.
-- =============================================================================

-- =============================================================================
-- STEP 1: DROP indexes with wrong names (old or duplicate)
-- =============================================================================

-- task_execution: ix_task_name → ix_task_execution_name
DROP INDEX IF EXISTS ix_task_name;

-- task_execution: ix_task_execution_parent_id → ix_task_execution_parent_task_execution_id
DROP INDEX IF EXISTS ix_task_execution_parent_id;

-- graph_execution: ix_graph_task_id → uq_graph_execution_task_execution_id (unique)
DROP INDEX IF EXISTS ix_graph_task_id;

-- graph_node_execution: ix_graph_node_graph_id → ix_graph_node_execution_graph_execution_id
DROP INDEX IF EXISTS ix_graph_node_graph_id;

-- workflow: ix_workflow_current_node → ix_workflow_current_graph_node_execution_id
DROP INDEX IF EXISTS ix_workflow_current_node;

-- graph_node_execution_result: ix_node_result_node_id → ix_node_result_node_execution_id
DROP INDEX IF EXISTS ix_node_result_node_id;

-- outbox_event: ix_outbox_event_event_type → ix_outbox_event_type
DROP INDEX IF EXISTS ix_outbox_event_event_type;

-- inbox_event: ix_inbox_event_event_type → ix_inbox_event_type
DROP INDEX IF EXISTS ix_inbox_event_event_type;

-- audit_event: ix_audit_event_event_type → ix_audit_event_type
DROP INDEX IF EXISTS ix_audit_event_event_type;

-- =============================================================================
-- STEP 2: DROP duplicate unique partial indexes (same table/columns/condition)
-- =============================================================================

-- graph_node_execution_input_payload: gneip_input_payload_current is a duplicate
-- of uq_gne_input_payload_current → both will be replaced by
-- uq_graph_node_execution_input_payload_is_current
DROP INDEX IF EXISTS gneip_input_payload_current;
DROP INDEX IF EXISTS uq_gne_input_payload_current;

-- graph_node_execution_output_payload: same pattern
DROP INDEX IF EXISTS gneop_output_payload_current;
DROP INDEX IF EXISTS uq_gne_output_payload_current;

-- task_execution_input_payload: uq_input_payload_current + uq_task_input_payload_current
-- are duplicates of each other → both replaced by uq_task_execution_input_payload_is_current
DROP INDEX IF EXISTS uq_input_payload_current;
DROP INDEX IF EXISTS uq_task_input_payload_current;

-- task_execution_output_payload: same pattern
DROP INDEX IF EXISTS uq_output_payload_current;
DROP INDEX IF EXISTS uq_task_output_payload_current;

-- =============================================================================
-- STEP 3: CREATE indexes with correct enterprise names
-- =============================================================================

-- ---- task_execution ----
CREATE INDEX IF NOT EXISTS ix_task_execution_name
    ON task_execution(name);

CREATE INDEX IF NOT EXISTS ix_task_execution_parent_task_execution_id
    ON task_execution(parent_task_execution_id);

-- ---- graph_execution ----
-- Unique index replaces the old non-unique ix_graph_task_id
CREATE UNIQUE INDEX IF NOT EXISTS uq_graph_execution_task_execution_id
    ON graph_execution(task_execution_id);

-- ---- graph_node_execution ----
CREATE INDEX IF NOT EXISTS ix_graph_node_execution_graph_execution_id
    ON graph_node_execution(graph_execution_id);

-- ---- workflow ----
CREATE INDEX IF NOT EXISTS ix_workflow_task_execution_id
    ON workflow(task_execution_id);

CREATE INDEX IF NOT EXISTS ix_workflow_current_graph_node_execution_id
    ON workflow(current_graph_node_execution_id);

-- ---- graph_node_definition ----
CREATE INDEX IF NOT EXISTS ix_graph_node_definition_graph_definition_id
    ON graph_node_definition(graph_definition_id);

-- ---- outbox_event ----
CREATE INDEX IF NOT EXISTS ix_outbox_event_type
    ON outbox_event(event_type);

CREATE INDEX IF NOT EXISTS ix_outbox_event_published_at
    ON outbox_event(published_at);

-- ---- inbox_event ----
CREATE INDEX IF NOT EXISTS ix_inbox_event_type
    ON inbox_event(event_type);

-- ---- audit_event ----
CREATE INDEX IF NOT EXISTS ix_audit_event_type
    ON audit_event(event_type);

-- ---- graph_node_execution_result ----
CREATE INDEX IF NOT EXISTS ix_node_result_node_execution_id
    ON graph_node_execution_result(graph_node_execution_id);

-- ---- task_execution_input_payload ----
CREATE INDEX IF NOT EXISTS ix_task_execution_input_payload_task_execution_id
    ON task_execution_input_payload(task_execution_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_task_execution_input_payload_is_current
    ON task_execution_input_payload(task_execution_id)
    WHERE is_current = true;

-- ---- task_execution_output_payload ----
CREATE INDEX IF NOT EXISTS ix_task_execution_output_payload_task_execution_id
    ON task_execution_output_payload(task_execution_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_task_execution_output_payload_is_current
    ON task_execution_output_payload(task_execution_id)
    WHERE is_current = true;

-- ---- graph_node_execution_input_payload ----
CREATE INDEX IF NOT EXISTS ix_graph_node_execution_input_payload_graph_node_execution_id
    ON graph_node_execution_input_payload(graph_node_execution_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_graph_node_execution_input_payload_is_current
    ON graph_node_execution_input_payload(graph_node_execution_id)
    WHERE is_current = true;

-- ---- graph_node_execution_output_payload ----
CREATE INDEX IF NOT EXISTS ix_graph_node_execution_output_payload_graph_node_execution_id
    ON graph_node_execution_output_payload(graph_node_execution_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_graph_node_execution_output_payload_is_current
    ON graph_node_execution_output_payload(graph_node_execution_id)
    WHERE is_current = true;

-- ---- graph_execution_state ----
CREATE INDEX IF NOT EXISTS ix_graph_execution_state_graph_execution_id
    ON graph_execution_state(graph_execution_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_graph_execution_state_is_current
    ON graph_execution_state(graph_execution_id)
    WHERE is_current = true;

-- =============================================================================
-- UNTOUCHED (already match convention, no action needed)
-- =============================================================================
-- ix_audit_event_occurred_at         ✅  audit_event(occurred_at)
-- ix_envelope_event_envelope_id      ✅  envelope_event(envelope_id)
-- ix_envelope_workflow_id            ✅  envelope(workflow_id)
-- ix_inbox_event_processed_at        ✅  inbox_event(processed_at)
-- ix_message_session_id              ✅  message(session_id)
-- ix_node_result_workflow_id         ✅  graph_node_execution_result(workflow_id)
-- ix_node_state_workflow_id          ✅  graph_node_execution_state(workflow_id)
-- ix_prompt_name                     ✅  prompt(name)
-- ix_rag_chunk_document_id           ✅  rag_chunk(document_id)
-- ix_rag_document_domain             ✅  rag_document(domain)
-- ix_rag_document_source_uri         ✅  rag_document(source_uri)
-- ix_runner_config_package_name      ✅  runner_config(package_name)
-- ix_graph_execution_graph_def_id    ⚠️  DB-only (not in code) — left intact

-- =============================================================================
-- NOTES
-- =============================================================================
-- 1. envelope_archive table does NOT exist in DB (migration 001 creates it but
--    either was never run or was dropped). Two indexes expected by code:
--      ix_envelope_archive_envelope_id, ix_envelope_archive_workflow_id
--    Cannot create without the table — handle separately.
--
-- 2. node_result / node_state table names in migration 001 differ from actual
--    DB tables (graph_node_execution_result / graph_node_execution_state). The
--    SQL above targets the actual DB table names. Code migration still needs
--    to be updated to match.
-- =============================================================================
