from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from shell.domain.entities.envelope import Envelope
    from shell.domain.value_objects.ids import EnvelopeId, WorkflowId


class EnvelopeRepository(Protocol):
    async def get_by_id(self, envelope_id: EnvelopeId) -> Envelope | None: ...
    async def save(self, envelope: Envelope) -> None: ...
    async def list_by_workflow(self, workflow_id: WorkflowId, limit: int | None = None, offset: int = 0) -> list[Envelope]: ...
    async def list_pending(self, workflow_id: WorkflowId, limit: int | None = None, offset: int = 0) -> list[Envelope]: ...


class EnvelopeArchive(Protocol):
    async def archive(self, envelope: Envelope) -> str: ...
    async def get(self, archive_uri: str) -> Envelope | None: ...
