from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from shell.domain.entities.task_execution import TaskExecution
    from shell.domain.value_objects.ids import TaskExecutionId
    from shell.domain.value_objects.task_execution_name import TaskExecutionName


class TaskExecutionRepository(Protocol):
    async def get_by_id(self, task_execution_id: TaskExecutionId) -> TaskExecution | None: ...
    async def get_by_name(self, name: TaskExecutionName) -> TaskExecution | None: ...
    async def get_current_by_id(self, id: TaskExecutionId) -> TaskExecution | None: ...
    async def get_current_by_name(self, name: TaskExecutionName) -> TaskExecution | None: ...
    async def save(self, task_execution: TaskExecution) -> None: ...
    async def list_current(self) -> list[TaskExecution]: ...
