from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from shell.domain.entities.task import Task
    from shell.domain.value_objects.ids import TaskId
    from shell.domain.value_objects.task_name import TaskName


class TaskRepository(Protocol):
    async def get_by_id(self, task_id: TaskId) -> Task | None: ...
    async def get_by_name(self, name: TaskName) -> Task | None: ...
    async def get_current_by_id(self, id: TaskId) -> Task | None: ...
    async def get_current_by_name(self, name: TaskName) -> Task | None: ...
    async def save(self, task: Task) -> None: ...
    async def list_current(self) -> list[Task]: ...
