from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from shell.domain.value_objects.ids import (
        EnvelopeId,
        GraphDefinitionId,
        GraphNodeDefinitionId,
        GraphExecutionId,
        MessageId,
        GraphNodeExecutionId,
        GraphNodeExecutionResultId,
        PromptId,
        RagChunkId,
        RagDocumentId,
        RunnerConfigId,
        SessionId,
        TaskExecutionId,
        WorkflowId,
    )


class IdGenerator(Protocol):
    def new_task_execution_id(self) -> TaskExecutionId: ...
    def new_workflow_id(self) -> WorkflowId: ...
    def new_envelope_id(self) -> EnvelopeId: ...
    def new_prompt_id(self) -> PromptId: ...
    def new_graph_node_execution_result_id(self) -> GraphNodeExecutionResultId: ...
    def new_runner_config_id(self) -> RunnerConfigId: ...
    def new_rag_document_id(self) -> RagDocumentId: ...
    def new_rag_chunk_id(self) -> RagChunkId: ...
    def new_session_id(self) -> SessionId: ...
    def new_message_id(self) -> MessageId: ...
    def new_graph_definition_id(self) -> GraphDefinitionId: ...
    def new_graph_node_definition_id(self) -> GraphNodeDefinitionId: ...
    def new_graph_execution_id(self) -> GraphExecutionId: ...
    def new_graph_node_execution_id(self) -> GraphNodeExecutionId: ...
