from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from shell.domain.value_objects.ids import (
        EnvelopeId,
        GraphDefinitionId,
        GraphDefinitionNodeId,
        GraphId,
        MessageId,
        NodeId,
        NodeResultId,
        PromptId,
        RagChunkId,
        RagDocumentId,
        RunnerConfigId,
        SessionId,
        TaskExecutionId,
        WorkflowId,
    )


class IdGenerator(Protocol):
    def new_task_execution_id(self) -> TaskExecutionId: ...
    def new_workflow_id(self) -> WorkflowId: ...
    def new_envelope_id(self) -> EnvelopeId: ...
    def new_prompt_id(self) -> PromptId: ...
    def new_node_result_id(self) -> NodeResultId: ...
    def new_runner_config_id(self) -> RunnerConfigId: ...
    def new_rag_document_id(self) -> RagDocumentId: ...
    def new_rag_chunk_id(self) -> RagChunkId: ...
    def new_session_id(self) -> SessionId: ...
    def new_message_id(self) -> MessageId: ...
    def new_graph_definition_id(self) -> GraphDefinitionId: ...
    def new_graph_definition_node_id(self) -> GraphDefinitionNodeId: ...
    def new_graph_id(self) -> GraphId: ...
    def new_node_id(self) -> NodeId: ...
