from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from shell.domain.execution.aggregates.task_execution import TaskExecution
    from shell.domain.execution.value_objects.task_execution_name import TaskExecutionName
    from shell.domain.execution.value_objects.ids import TaskExecutionId, WorkflowId


class TaskExecutionRepository(Protocol):
    async def get_by_id(self, task_execution_id: TaskExecutionId) -> TaskExecution | None: ...
    async def get_by_name(self, name: TaskExecutionName) -> TaskExecution | None: ...
    async def get_current_by_id(self, id: TaskExecutionId) -> TaskExecution | None: ...
    async def get_current_by_name(self, name: TaskExecutionName) -> TaskExecution | None: ...
    async def get_by_workflow_id(
        self, workflow_id: WorkflowId
    ) -> list[TaskExecution]: ...
    async def save(self, task_execution: TaskExecution) -> None: ...
    async def list_current(self) -> list[TaskExecution]: ...
