services:
  shell-definition:
    build:
      context: ../../..
      dockerfile: shell/definition/docker/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ../../../shell_dev:/app/shell_dev
