from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, TypeVar

if TYPE_CHECKING:
    from collections.abc import Sequence

TRepository = TypeVar("TRepository")


class UnitOfWork(Protocol):
    def repository(self, repo_type: type[TRepository]) -> TRepository: ...

    def stage_events(self, events: Sequence[object]) -> None: ...

    async def save(self, repo_type: type, aggregate: object) -> None: ...

    def stage_messages(self, messages: list[object]) -> None: ...

    @property
    def events(self) -> Sequence[object]: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...

    async def __aenter__(self) -> UnitOfWork: ...

    async def __aexit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...
