from __future__ import annotations

from typing import Protocol, TypeVar

TRepository = TypeVar("TRepository")


class UnitOfWork(Protocol):
    def repository(self, repo_type: type[TRepository]) -> TRepository: ...

    def stage_events(self, events: list) -> None: ...

    def stage_messages(self, messages: list) -> None: ...

    @property
    def events(self) -> list: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...

    async def __aenter__(self) -> UnitOfWork: ...

    async def __aexit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...
