from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from shell.domain.execution.aggregates.graph_execution.value_objects.graph_execution_id import (
        GraphExecutionId,
    )
    from shell.domain.execution.aggregates.graph_node_execution.graph_node_execution import (
        GraphNodeExecution,
    )
    from shell.domain.execution.aggregates.graph_node_execution.value_objects.graph_node_execution_id import (
        GraphNodeExecutionId,
    )
    from shell.domain.platform.value_objects.exists_result import ExistsResult


class GraphNodeExecutionRepository(Protocol):
    async def get_by_id(self, node_id: GraphNodeExecutionId) -> GraphNodeExecution | None: ...

    async def delete(self, id: GraphNodeExecutionId) -> None: ...
    async def exists(self, id: GraphNodeExecutionId) -> ExistsResult: ...
    
    async def save(self, node: GraphNodeExecution) -> None: ...

    async def delete(self, id: GraphNodeExecutionId) -> None: ...
    async def exists(self, id: GraphNodeExecutionId) -> ExistsResult: ...
    
    async def list_by_ids(self, ids: list[GraphNodeExecutionId]) -> list[GraphNodeExecution]: ...

    async def delete(self, id: GraphNodeExecutionId) -> None: ...
    async def exists(self, id: GraphNodeExecutionId) -> ExistsResult: ...
    
    async def list_by_graph_execution_id(
        self, graph_execution_id: GraphExecutionId
    ) -> list[GraphNodeExecution]: ...

    async def delete(self, id: GraphNodeExecutionId) -> None: ...
    async def exists(self, id: GraphNodeExecutionId) -> ExistsResult: ...
    
    async def get_next_pending(
        self, graph_execution_id: GraphExecutionId
    ) -> GraphNodeExecution | None: ...
    async def delete(self, id: GraphNodeExecutionId) -> None: ...
    async def exists(self, id: GraphNodeExecutionId) -> ExistsResult: ...
    