CONFIG_DIR = 'config'
CONFIG_YAML = 'config.yaml'
MANIFEST_YAML = 'manifest.yaml'

DOT_NODE = '.node'

DIR_INPUT = 'input'
DIR_OUTPUT = 'output'
DIR_LOGS = 'logs'
DIR_TEMP = 'temp'
DIR_ARCHIVE = 'archive'
DIR_SCRIPTS = 'scripts'
DIR_PROMPT = 'prompt'
DIR_STAGE = 'stage'
DIR_TASK = 'task'

DIR_STAGE_ACTIVE = 'active'
DIR_STAGE_PENDING = 'pending'
DIR_STAGE_HISTORY = 'history'
DIR_STAGE_IGNORED = 'ignored'
DIR_STAGE_DEAD = 'dead'
DIR_STAGE_DONE = 'done'
