from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from shell.domain.definition.value_objects.ids import (
        GraphDefinitionId,
        GraphNodeDefinitionId,
        RagChunkId,
        RagDocumentId,
        RunnerConfigId,
    )
    from shell.domain.execution.aggregates.workflow_state.value_objects.workflow_state_id import (
        WorkflowStateId,
    )
from shell.domain.execution.value_objects.ids import (
    GraphExecutionId,  # noqa: TC002 -- używane w sygnaturach metod IdGenerator
    GraphNodeExecutionId,  # noqa: TC002 -- używane w sygnaturach metod IdGenerator
    GraphNodeExecutionResultId,  # noqa: TC002 -- używane w sygnaturach metod IdGenerator
    SessionId,  # noqa: TC002 -- używane w sygnaturach metod IdGenerator
    TaskExecutionId,  # noqa: TC002 -- używane w sygnaturach metod IdGenerator
    TaskExecutionStateId,  # noqa: TC002 -- używane w sygnaturach metod IdGenerator
    WorkflowId,  # noqa: TC002 -- używane w sygnaturach metod IdGenerator
)
from shell.domain.platform.aggregates.message.value_objects.message_id import MessageId


class IdGenerator(Protocol):
    def new_task_execution_id(self) -> TaskExecutionId: ...
    def new_workflow_id(self) -> WorkflowId: ...
    def new_message_id(self) -> MessageId: ...
    def new_graph_node_execution_result_id(self) -> GraphNodeExecutionResultId: ...
    def new_runner_config_id(self) -> RunnerConfigId: ...
    def new_rag_document_id(self) -> RagDocumentId: ...
    def new_rag_chunk_id(self) -> RagChunkId: ...
    def new_session_id(self) -> SessionId: ...
    def new_graph_definition_id(self) -> GraphDefinitionId: ...
    def new_graph_node_definition_id(self) -> GraphNodeDefinitionId: ...
    def new_graph_execution_id(self) -> GraphExecutionId: ...
    def new_graph_node_execution_id(self) -> GraphNodeExecutionId: ...
    def new_task_execution_state_id(self) -> TaskExecutionStateId: ...
    def new_workflow_state_id(self) -> WorkflowStateId: ...
